# Generated by Django 5.2.4 on 2025-08-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_options_productreview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productreview",
            name="user",
        ),
    ]
