# Generated by Django 5.2.4 on 2025-08-21 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_productreview_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="updated_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 8, 21, 15, 10, 4, 342171, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
