# Generated by Django 5.2.4 on 2025-08-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_productreview_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
