# Generated by Django 5.2.4 on 2025-08-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_productimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="is_featured",
        ),
    ]
