# Generated by Django 5.2.5 on 2025-08-31 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_cart_id"),
        (
            "products",
            "0003_rename_description_review_comment_remove_review_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
    ]
