# Generated by Django 5.2.5 on 2025-09-02 14:38

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_cartitem_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Not Paid", "Not Paid"),
                    ("Ready To Ship", "Ready To Ship"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                ],
                default="Not Paid",
                max_length=20,
            ),
        ),
    ]
