# Generated by Django 5.2.5 on 2025-09-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_rename_description_review_comment_remove_review_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
